### ISSUE TITLE
[story] Upload a file to a dataset in the DataStore

### ISSUE THREAD

**Issue by rgrp** [openspending/os-upload#1]
As a **(Data) Contributor** I want to **upload a file to the datastore** so that the **file is uploaded and ready to use in OS.org**

* Is this for an "existing" dataset or a new one?
  * What does existing dataset mean? It could mean exists on openspending.org (OS.org) or on the DataStore (data.openspending.org). Right now we will mean on the DataStore but will check in the background to see if something already exists on OS.org. Medium term we should have copied everything from OS.org to DataStore and updated the workflow so this is automatic
  * Ans: we should support both
* How do permissions work? What is a user allowed to do?
  * We should mimic current permissions: i.e. CRUD should follow from what you can do on OS.org. Note for this we need https://github.com/openspending/openspending/issues/687
* Note we could have a simpler implementation where we don't upload to a dataset but just to the user's space
  * This would definitely 

## Implementation

Existing dataset:

* [ ] check you are logged in #2 
* [ ] dataset chooser that does look up on DataStore
* [ ] check dataset exists, if not exists prompt to create and then see create path below
* [ ] check your permissions - fail if not authorized for what you want to do
* [ ] upload interface and handle upload
* [ ] upload the file and update the dataset package.json
* [ ] report success to user

New dataset

* ...

Extras:

* [ ] allow for uploading multiple files at once (see e.g. plupload frontend)

**Comment by pwalsh** [comment]
I'm closing old issues.
