### ISSUE TITLE
Managing the DataPackage object

### ISSUE THREAD

**Issue by pwalsh** [openspending/os-upload#27]
@gvidon some questions:
1. In DataPackagist, the JSON Editor takes care of managing our Data Package object, right? If I remember correctly, this is why we had no need there for using [datapackage-read](https://github.com/okfn/datapackage-read) or [datapackage-init](https://github.com/okfn/datapackage-init)
2. What is the current implementation in os-import for managing the DataPackage object? We want to get this right, as it holds the state of user data across all steps. Particularly, we want to ensure that this uses modules we already have (such as those mentioned above), and that the logic is clearly delineated from UI logic (so we can unit test it).

**Comment by gvidon** [comment]
@pwalsh currently data package created in a very simple way — just rendering template https://github.com/openspending/os-import/blob/develop/os-import/src/templates/datapackage.hbs

I thought about it, and agree that template rendering should be replaced with a lib which will take params and generate json which is up to date with data package schema.

**Comment by pwalsh** [comment]
@gvidon this is critical. the datapackage is the model in which (almost) all state for the current import is saved. This should be done in current sprint.

**Comment by gvidon** [comment]
@pwalsh ok, will use _datapackage-init_ for these actions.

**Comment by gvidon** [comment]
@pwalsh @rgrp can't use https://github.com/okfn/datapackage-init/ as it relies on `fs` module of node.js which fails in a browser environment — https://github.com/okfn/datapackage-init/blob/master/index.js#L124

**Comment by rufuspollock** [comment]
@gvidon there's been a discussion before about refactoring datapackage-init a bit to support this - cf the online demo in that repo e.g. https://github.com/okfn/datapackage-init/issues/18 and https://github.com/okfn/datapackage-init/issues/2 - given that you will need this kind of workflow anyway here I suggest we try and work on datapackage-init to support what we need (or at least spec out alternative).

**Comment by pwalsh** [comment]
@gvidon 

Same issue we had a few months ago with [datapackage-validate](https://github.com/okfn/datapackage-validate), which you solved there. Can we not take a similar approach here?

**Comment by gvidon** [comment]
@pwalsh in case of datapackage-validate we replaced file system calls with xhr. It will not work with datapackage-init as it searches for files to be added as resources. These files are uploaded by user.

**Comment by gvidon** [comment]
@pwalsh probably removing check for existence of `filepath` when adding resource and manually providing file size and other properties will solve the problem.

But in case of manually defining resource properties what is the benefit of using `createResourceEntry` of datapackage-init?

**Comment by pwalsh** [comment]
@gvidon real benefit of `createResourceEntry` or any other methods available in `datapackage-init` is simply that we have a single library that is responsible for things, and by updating the lib we update the ecosystem, rather than having multiple same or similar implementations around. I know that is not exactly the answer you were looking for :).

For now, If you think the work to get `datapackage-init` in a workable state for clean use in both server and client is significant (eg: more than a full day of work), then I suggest you do the following:
1. Open one or many issues on the `datapackage-init` repo for what we need to change for our use case
2. Proceed with a similar implementation, as long as you have a single point of truth for the data package, and a model-based approach to maintaining the object, as the simple template is not a great solution as we build further out on this.

What do you think?

**Comment by gvidon** [comment]
@pwalsh yes, I understand benefits of the lib which adds abstraction layer and is responsible for managing object according to a spec.

But even with such a lib for datapackage you can't avoid working directly with root properties of data package like `name` or `title`. The only benefits I can see are calls like

``` javascript
// This method will parse file get its properties, like file size, generate schema and create .resources entry
datapackage.createResource(<file to be parsed>)
```

or

``` javascript
// Create mapping property, according to spec
datapackage.addAmount(<column to be mapped into Amount concept>)
```

But in case of `.createResource()` if you can't read the file, you have to do it manually and pass to the method. So there is no difference between:

``` javascript
// Add resource by calling lib method
datapackage.createResource({
  bytes: 169
  name: "decent"
  path: "decent.csv"
  schema: <schema generated by jts infer>
})
```

and

``` javascript
// Add resource by changing object directly
datapackage.resources.push({
  bytes: 169
  name: "decent"
  path: "decent.csv"
  schema: <schema generated by jts infer>
})
```

I will work on datapackage model after current task, will try to add as much reasonable abstraction as possible.

**Comment by pwalsh** [comment]
Closing in favor of notes in #30
