### ISSUE TITLE
Clearly delineate UI code from logic

### ISSUE THREAD

**Issue by pwalsh** [openspending/os-upload#28]
@gvidon as with DataPackagist, we need to strictly delineate UI "glue" and interactions from the main logic of the application. 

We are using most of the libraries from DataPackagist anyway, but please do a quick review of work done so far and ensure that we are enforcing such a delineation. 

Add comments here for any areas we might need to address.

Also inviting @pwalsh @danfowler @rgrp to use this issue to dump comments on this as we iterate on `os-import` this sprint.

**Comment by gvidon** [comment]
@pwalsh @danfowler @rgrp at the moment there is just single method I would move out of UI area — https://github.com/openspending/os-import/blob/develop/os-import/src/scripts/components/ui/create-dp/upload.js#L62

There is CSV parsing, schema infering and GoodTables validation. I would also call it more relevant to what it does.

**Comment by pwalsh** [comment]
Closing in favor of notes in #30
